solver 2
method 1
input_type 1
matrix_type 1
levels 1
info_file doug_info.dat
freedom_lists_file doug_element.dat
elemmat_rhs_file doug_system.dat
coords_file doug_coord.dat
freemap_file doug_freemap.dat
freedom_mask_file ./NOT.DEFINED.freedom_mask_file
number_of_blocks 1
initial_guess 2
start_vec_file ./NOT.DEFINED.start_vec_file
start_vec_type 2
solve_tolerance 1.0e-12
solution_format 2
solution_file solution.xdr
debug 0
verbose 10
plotting 0
maxcie 4
cutbal 3
