#!/bin/csh
set j=`ps -lfU $USER |grep -v grep | grep -v csh | grep $* |awk '/eero/{print $4}'` 
if ( "$j" != "" ) then
  echo $* : $j
  @ i =1
  while ( $i < $#j )
    @ k =($i + 1) 
    echo "$j[$i] $j[$k]"
    @ i =($i + 2) 
  end
else
  echo $* -- pole...
endif

